steps:
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "cb-build", "-f", "Dockerfile.build", "."]
- name: cb-build
  args: ["cp", "/go/src/cb/cb", "/workspace"]
- name: gcr.io/cloud-builders/docker
  args: ["build", "-t", "hiroshi3110/cb", "."]
images:
- hiroshi3110/cb
